### ISSUE TITLE
Where like query in lumen is not working !

### ISSUE THREAD

**Issue by bthnbstrk** [chr15k/laravel-mysql-encrypt#2]
Hello,

Thank you for code,  i think this lib not supported like query eloquent orm.  
For example: **XMODEL::where("email_address", 'like', '%'.'outlook.com'.'%')-first();**

How can do solve this ? 
Thanks.

**Comment by chr15k** [comment]
Hi @bthnbstrk thanks for raising this issue. However, just to let you know, I'm no longer maintaining this package. But to answer your question, this should work:

```
User::whereEncrypted('email_address', '%'.'outlook.com'.'%')->first();
```
